application:
  root: # setting defaults to repo root dir if undefined here
  # WARNING - it may be necessary to manually populate root with an escaped string

# OPTIONAL define default parameters
default_config:
  database: 
  host: 
  port: 
  xls_config: 
  outpath: # defaults to %temp% on script run if undefined in settings

# OPTIONAL geometries for protected data will not be exported, only intersect summary stats
protected_data:
  tables:
    - YOUR_SCHEMA.SECRET_TABLE
